const houses = [
  {
    id: '1',
    title: 'Entire guest suite',
    location: 'Hyderabad',
    image: require('../assets/house1.jpg'),
    details: `This building is located in road no 12 banjara hills, withing walking distance of shops...`,
    price: 10000,
    for: 'For Rent',
    type: 'Flat',
    subType: 'BHK',
    bedrooms: 2,
    bathrooms: 1,
    kitchens: 1,
    face: 'Easet',
    area: 300,
    furnished: 'Semi furnished',
    floor: 1,
    floorCount: 5,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
  {
    id: '2',
    title: 'Private room in house',
    location: 'Banjara hills, Hyderabad',
    image: require('../assets/house2.jpg'),
    details: `This building is located in Jubilee hills road no 52, withing walking distance of shops...`,
    price: 1200000000,
    for: 'For Sale',
    type: 'Villa',
    subType: 'BHK',
    bedrooms: 2,
    bathrooms: 1,
    kitchens: 1,
    face: 'Easet',
    area: 600,
    furnished: 'Fully furnished',
    floor: 2,
    floorCount: 6,
    interiors: [
      require('../assets/interior1.jpg'),
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
  {
    id: '3',
    title: 'Entire apartment',
    location: 'Hyderabad',
    image: require('../assets/house3.jpg'),
    details: `This building is located in Hitech city, withing walking distance of shops...`,
    price: 15000,
    for: 'For Rent',
    type: 'Flat',
    subType: 'BHK',
    bedrooms: 2,
    bathrooms: 1,
    kitchens: 1,
    face: 'Easet',
    area: 300,
    furnished: 'Semi furnished',
    floor: 1,
    floorCount: 5,
    interiors: [
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
      require('../assets/interior1.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
  {
    id: '4',
    title: 'Private room in apartment',
    location: 'Dilsukhnagar, Hyderabad',
    image: require('../assets/house4.jpg'),
    details: `This building is located in Madhapur, withing walking distance of shops...`,
    price: 11500000,
    for: 'For Sale',
    type: 'Flat',
    subType: 'BHK',
    bedrooms: 2,
    bathrooms: 1,
    kitchens: 1,
    face: 'Easet',
    area: 300,
    furnished: 'Semi furnished',
    floor: 1,
    floorCount: 5,
    interiors: [
      require('../assets/interior2.jpg'),
      require('../assets/interior1.jpg'),
      require('../assets/interior3.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
  {
    id: '5',
    title: 'Private room in apartment',
    location: 'Dilsukhnagar, Hyderabad',
    image: require('../assets/house4.jpg'),
    details: `This building is located in Madhapur, withing walking distance of shops...`,
    price: 100000,
    for: 'For Lease',
    type: 'Flat',
    subType: 'BHK',
    bedrooms: 2,
    bathrooms: 1,
    kitchens: 1,
    face: 'Easet',
    area: 300,
    furnished: 'Semi furnished',
    floor: 1,
    floorCount: 5,
    interiors: [
      require('../assets/interior2.jpg'),
      require('../assets/interior1.jpg'),
      require('../assets/interior3.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
  {
    id: '6',
    title: 'Entire apartment',
    location: 'Hyderabad',
    image: require('../assets/house3.jpg'),
    details: `This building is located in Hitech city, withing walking distance of shops...`,
    price: 15000,
    for: 'For Lease',
    type: 'Flat',
    subType: 'BHK',
    bedrooms: 3,
    bathrooms: 2,
    kitchens: 1,
    face: 'Easet',
    area: 400,
    furnished: 'Fully furnished',
    floor: 1,
    floorCount: 6,
    interiors: [
      require('../assets/interior2.jpg'),
      require('../assets/interior3.jpg'),
      require('../assets/interior1.jpg'),
    ],
    ownerInfor: {
      name: 'Akshay',
      mobileNo: 238901290,
      email: 'example@host.com',
    },
  },
];

export default houses;
