export const ADD_PROPERTY_REQ = 'ADD_PROPERTY_REQ';
export const ADD_PROPERTY_SUCCESS = 'ADD_PROPERTY_SUCCESS';
export const ADD_PROPERTY_FAIL = 'ADD_PROPERTY_FAIL';

export const GET_ALL_PROPERTIES_REQ = 'GET_ALL_PROPERTIES_REQ';
export const GET_ALL_PROPERTIES_SUCCESS = 'GET_ALL_PROPERTIES_SUCCESS';
export const GET_ALL_PROPERTIES_FAIL = 'GET_ALL_PROPERTIES_FAIL';

export const GET_FILTERED_PROPS_REQ = 'GET_FILTERED_PROPS_REQ';
export const GET_FILTERED_PROPS_SUCCESS = 'GET_FILTERED_PROPS_SUCCESS';
export const GET_FILTERED_PROPS_FAIL = 'GET_FILTERED_PROPS_FAIL';
