export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const GET_USER_BY_ID_REQ = 'GET_USER_BY_ID_REQ';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BYSUCCESS';
export const GET_USER_BY_ID_FAIL = 'GET_USER_BYFAIL';

export const ADD_TO_WISHLIST_REQ = 'ADD_TO_WISHLIST_REQ';
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS';
export const ADD_TO_WISHLIST_FAIL = 'ADD_TO_WISHLIST_FAIL';
